ecommerce/routes.py
import os
from flask import current_app as app
from flask import Blueprint, flash, redirect, render_template, request, url_for
from werkzeug.utils import secure_filename
from . import db
from .db_models import Orders, User, Cart, Product, Shipping, Payment, Purchase_history, OrderedProduct
from flask_login import login_required, current_user
from werkzeug.security import generate_password_hash, check_password_hash


# creating a blueprint for routes.py
routes = Blueprint('routes', __name__)


# File integrity checker 
ALLOWED_EXTENSIONS = {'txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif'}
def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


# index.html 
@routes.route('/')
def index():

    return render_template('index.html', user=current_user)

# products.html
@routes.route('/products', methods=['GET', 'POST'])
def products():
    products = Product.query.all()
    #print(products)
    return render_template('products.html', user=current_user, products=products)

@routes.route('/products/<string:category>', methods=['GET', 'POST'])
def products_by_category(category):
    curr_category = category
    products = Product.query.all()
    prod_by_category = Product.query.filter_by(category=curr_category)
    return render_template('products.html', user=current_user, curr_category=curr_category, prod_by_category=prod_by_category, products=products)
#{{ url_for('routes.products', user=current_user, category=curr_category) }}

@routes.route('/productDisplay/<int:product_id>', methods=['GET', 'POST'])
def productDisplay(product_id):

    product = Product.query.get_or_404(product_id)
    product_owner = User.query.get_or_404(product.user_id)
    location = product_owner.user_address
    if location:
        splitlocation = location.split(',')
        located = splitlocation[3] + ',' + splitlocation[5]
        print(located)
    
    id = current_user.get_id()
    prod_display_user = id
    if request.method == 'POST':

        new_cart = Cart(user_id=id, product_id=product_id, quantity=1)
        db.session.add(new_cart)
        db.session.commit()
        flash("Added to cart!", category="success")
        return redirect(url_for('routes.products'))
#       return render_template('productDisplay.html', user=current_user, product=product, owner=product_owner, location=located)
    if location:
        return render_template('productDisplay.html', user=current_user, product=product, owner=product_owner, location=located)
    else:
        return render_template('productDisplay.html', user=current_user, product=product, owner=product_owner)
    
@routes.route('/addProduct', methods=['GET', 'POST'])
@login_required
def addProduct():
    id = current_user.get_id()
    add_prod_user = User.query.get(id) # assign id to user_to_update

    p_name = request.form.get("p_name")
    p_price = request.form.get("p_price")
    p_desc = request.form.get("p_desc")
    category = request.form.get("category")

    #print(file.filedata)
    if request.method == 'POST':

        file = request.files['uploadedFile']
        print(file.filename)
        print(file)
        print(file.read())

        if len(p_name) < 4:
            flash("Invalid product name", category="error")
        elif p_price.isdigit() == False:
            flash("Invalid price!", category="error")
        elif len(p_desc) < 5:
            flash("Invalid description!", category="error")
        elif len(category) < 3:
            flash("Invalid category", category="error")
        else:
            # check if the post request has the file part
            if 'uploadedFile' not in request.files:
                flash('No file part', category="error")
                return redirect(url_for('routes.addProduct'))
            file = request.files["uploadedFile"]
            # if user does not select file, browser also
            # submit an empty part without filename
            if file.filename == '':
                flash('No selected file')
                return redirect(url_for('routes.addProduct'))
            if file and allowed_file(file.filename):
                filename = secure_filename(file.filename)
                file.seek(0)
                file.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))
                new_product = Product(user_id=id, product_name=p_name, prod_price=p_price, prod_desc=p_desc, category=category, prod_owner=id, filename=filename)
                db.session.add(new_product)
                db.session.commit()
                #return redirect(url_for('uploaded_file', filename=filename))
            
        flash("Product was added!", category="success")
        return render_template('addProduct.html', user=current_user)
    
    return render_template('addProduct.html', user= current_user )
 
# accountManagement.html
@routes.route('/shipping', methods=['GET', 'POST'])
@routes.route('/accountManagement', methods=['GET', 'POST'])
@login_required
def accountManagement():
    # set the current user ID
    id = current_user.get_id()
    user_to_update = User.query.get(id) # assign id to user_to_update

    # gathering all the form data from accountManagement.html
    username = request.form.get("update_username")
    password1 = request.form.get("password1")
    password2 = request.form.get("update_password2")
    email = request.form.get("update_email")
    saddress1 = request.form.get("update_s_address1")
    saddress2 = request.form.get("update_s_address2")
    scity = request.form.get("update_s_city")
    sstate = request.form.get("update_s_state")
    szip = request.form.get("update_s_zip_code")
    scountry = request.form.get("update_s_country")
    baddress1 = request.form.get("update_b_addres1")
    baddress2 = request.form.get("update_b_address2")
    bcity = request.form.get("update_b_city")
    bstate = request.form.get("update_b_state")
    bzip = request.form.get("update_b_zip_code")
    bcountry = request.form.get("update_b_country")

    if request.method == 'POST':
        print("Triggered")
        # store the address
        saddress = ''
        baddress = ''

        if username:
            print(username)
            user_to_update.user_name = username
            db.session.commit()
            flash('Sucessfully updated your information!', category='success')
        if password1:
            print('exist')
            if check_password_hash(user_to_update.password, password1):
                print('matches')
                if len(password1) > 7:
                    print('length')
                    user_to_update.password = generate_password_hash(password2, method='pbkdf2:sha256')
                    db.session.commit()
                    flash('Sucessfully updated your information!', category='success')
                else:
                    flash('Password must be greater than 7 characters.', category='error')
            else:
                flash('Password doesn\'t match existing password!', category='error')
        if email:
            temp_email = email
            user_to_update.user_email = email
            db.session.commit()
            if temp_email != user_to_update.user_email:
                flash('Sucessfully updated your information!', category='success')

        # shipping address
        if saddress2:
            saddress = saddress + saddress2 + ', '
        if saddress1:
            saddress = saddress + saddress1 + ', '
        if scity:
            saddress = saddress + scity + ', '
        if sstate:
            saddress = saddress + sstate + ', '
        if szip:
            saddress = saddress + szip + ', ' 
        if scountry:
            saddress = saddress + scountry
        #if saddress != '':
            #flash('Sucessfully updated your information!', category='success')

        # billing address
        if baddress2:
            baddress = baddress + baddress2 + ', '
        if baddress1:
            baddress = baddress + baddress1 + ', '
        if bcity:
            saddress = baddress + bcity + ', '
        if bstate:
            saddress = baddress + bstate + ', '
        if szip:
            baddress = baddress + bzip + ', ' 
        if scountry:
            baddress = baddress + bcountry + ', '
        #if baddress != '':
            #flash('Sucessfully updated your information!', category='success')
        
        # adding the address into the database if baddress is same as shipping we take saddress information
        if len(saddress) > 1:

            # update user's normal address
            user_to_update.user_address = saddress

            # query the shipping table for the existence of user and certain address
            # to prevent from creating multiple rows with the same id and address
            existing_info_s = Shipping.query.filter_by(user_id=id, shipping_addr= saddress).first()
            # if the check for the user and address came back positive
            if existing_info_s:
                existing_info_s.shipping_addr = saddress # we leave the address the same
            else:
                new_shipping = Shipping(user_id=id, shipping_addr=saddress) # we create a new shipping id 
                db.session.add(new_shipping)

            db.session.commit()
            flash('Sucessfully updated your information!', category='success')

        if len(baddress) > 5:

            # query the Payment table for the existence of user and certain address
            # to prevent from creating multiple rows with the same id and address
            existing_info_b = Payment.query.filter_by(user_id=id, billing_addr= baddress).first()
            if existing_info_b:
                existing_info_b.billing_addr = baddress # leave everything the same
            else:
                # create a new Payment
                new_payments = Payment(user_id=id, card_num=None, card_holder_name=None, card_exp=None, card_pin=None, billing_addr=baddress)

ecommerce/templates/accountManagement.html
{% extends "base.html" %} {% block title%} Account Management {% endblock %} {% block content
%}
<div class="container">
  <div id="outer__account__management">
    <div class="account__management" id="account__management__main">
      <h1 id="account__management__title">My Account</h1>
      <form id="account-details" method="POST">
        <div class="input__group">
          {% if user %}
          <label for="username"
            >Username: <strong>{{ user.user_name }}</strong></label
          >
          <input
            type="text"
            class="update__info"
            id="username"
            name="update_username"
            placeholder="New username"
          />
        </div>
        <div class="input__group">
          <label for="password">Current Password:</label>
          <input
            type="password"
            class="update__info"
            id="password"
            name="password1"
            placeholder="Current password"
          />
        </div>
        <div class="input__group">
          <label for="password">Password:</label>
          <input
            type="password"
            class="update__info"
            id="password"
            name="update_password2"
            placeholder="New password (Current password required)"
          />
        </div>
        <div class="input__group">
          <label for="email"
            >Email: <strong>{{ user.user_email }}</strong></label
          >
          <input type="text" class="update__info" id="email" name="update_email" placeholder="New email"/>
        </div>
        <label>Address:</label> <br>
        {% if user.user_address %} 
        {% set addr_List = user.user_address.split(',') %}
            <strong> {{ addr_List[0] + ', ' + addr_List[1] + ',' }}
            <br>
            {{ addr_List[2] + ' ' + addr_List[3] + ', ' + addr_List[4] + ','}}
            <br>
            {{ addr_List[5] }}
            </strong>
            {% endif %}
            <br><br>
        <div class="shipping__extra">
          <div>
            <label for="update-shipping" id="update-shipping-addr">Update shipping address: </label>
          </div>
          <div>
            <input type="checkbox" onchange="updateBillingCheckBox()" stored_value='value' id="update-shipping" name='update-shipping' /> 
          </div>
        </div>
        <div class="input__group" id="shipping-address">
          <h2>
            Shipping Address 
          </h2>
          <div class="input__group">
            <label>Address line 1:</label>
            <input type="text" class="update__info" name="update_s_address1" placeholder="Address line 1"/>
            <label>Address line 2:</label>
            <input type="text" class="update__info" name="update_s_address2" placeholder="Address line 2 (Optional)"/>
            <label>City:</label>
            <input type="text" class="update__info" name="update_s_city" placeholder="City"/>
            <label>State:</label>
            <input type="text" class="update__info" name="update_s_state" placeholder="State"/>
            <label>Zip code:</label>
            <input type="text" class="update__info" name="update_s_zip_code" placeholder="Zip-code"/>
            <label>Country:</label>
            <input type="text" class="update__info" name="update_s_country" placeholder="Country"/>
          </div>
        </div>
        <div class="input__group" id="billing-address">
          <h2>
            Billing Address
          </h2>
          <label>Address line 1:</label>
            <input type="text" class="update__info" name="update_b_address1" placeholder="Address line 1"/>
            <label>Address line 2:</label>
            <input type="text" class="update__info" name="update_b_address2" placeholder="Address line 2 (Optional)"/>
            <label>City:</label>
            <input type="text" class="update__info" name="update_b_city" placeholder="City"/>
            <label>State:</label>
            <input type="text" class="update__info" name="update_b_State" placeholder="State"/>
            <label>Zip code:</label>
            <input type="text" class="update__info" name="update_b_zip_code" placeholder="Zip-code"/>
            <label>Country:</label>
            <input type="text" class="update__info" name="update_b_country" placeholder="Country"/>
          </div>
          <label>Billing address:</label>
          <div class="billing__extra">
            <div>
              <label for="same-as-shipping" id="same__as__addr">Same as Shipping Address: </label>
            </div>
            <div>
              <input type="checkbox" onchange="updateBillingCheckBox()" stored_value='value'id="same-as-shipping" name='same-as-shipping' checked/> 
            </div>
          </div>
          <button type="submit">Update Account</button>
        </div>
        {% endif %}
      </form>
    </div>
  </div>
  <div class="container">
    <div id="outer__account__management">
      <div class="account__management" id="sell__product">
        <a href="{{ url_for('routes.addProduct') }}" id="sell__a__product">
          <button type="submit" id="sell__a__product">Sell a Product</button> 
        </a>
        
      </div>
    </div>
  </div>
</div>

{% endblock %}

ecommerce/templates/addProduct.html
{% extends "base.html" %} {% block title%} Home {% endblock %} {% block content
%}
<div id="outer__add__product">
  <div id="add__product__main" style="display: show">
    <h1 id="add__product__title">Add Product</h1>
    <form id="add__product" method="POST" enctype="multipart/form-data">
      <label for="p_name">Product details:</label>
      <div id="add__product__name">
        <input
          type="text"
          class="update__info"
          id="p_name"
          name="p_name"
          placeholder="Name of Product"
          required
        />
        <input
          type="text"
          class="update__info"
          id="p_price"
          name="p_price"
          placeholder="Product price $"
          rows="5"
          required
        />
        <input
          type="text"
          class="update__info"
          id="category"
          name="category"
          placeholder="Category"
          required
        />
      </div>
      <label for="email">Product description: </label>
      <div id="add__product__name">
        <textarea
          type="text"
          class="update__info"
          id="p_desc"
          name="p_desc"
          placeholder="Entere a description ... "
          rows="8"
          required
        >
        </textarea>
      </div>
      <input type="file" name="uploadedFile" id="file__upload" />
      <button type="submit">Add product</button>
    </form>
  </div>
</div>
{% endblock %}

ecommerce/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!--<link 
      href="https://cdn.jsdelivr.net/npm/boosted@5.2.3/dist/css/boosted.min.css" 
      rel="stylesheet" integrity="sha384-zYFw+mxKy6r9zpAc1NoGiYBfQmxfvg7ONEMr81WeU+WLPPaLC9QTrNGFJTBi3EIn" 
      crossorigin="anonymous"
    /> -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <link
      href="https://getbootstrap.com/docs/5.2/assets/css/docs.css"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='style.css') }}"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"
    />
    <title>{% block title %} J's Prints {% endblock %}</title>
  </head>
  <body>
    <div class="container__main">
      <header class="my__header">
        <a href="{{ url_for('routes.index') }}"
          ><img
            id="logo"
            src="{{ url_for('static', filename='images/logo-no-background-resized-3.png') }}"
            alt="logo"
        /></a>
        <nav>
          <ul id="nav__links">
            <form action="{{ url_for('routes.search') }}" method="get">
              <input type="text" name="q" placeholder="Search...">
              <button type="submit">Search</button>
            </form>
            {% if user.is_authenticated %}
            <li><a href="{{ url_for('authentication.logout') }}">Logout</a></li>
            <li>
              <a href="{{ url_for('routes.accountManagement') }}">Account</a>
            </li>
            <li>
              <a href="{{ url_for('routes.shoppingCart') }}"
              <i class="bi bi-cart4" style="font-size: 1rem;"></i></a>
            </li>
            {% else %}
            <li><a href="{{ url_for('authentication.login') }}">Login</a></li>
            <li id="shopping__cart__logo">
              <a href="{{ url_for('routes.shoppingCart') }}"
                ><i class="bi bi-cart4" style="font-size: 1rem;"></i></a>
            </li>
            {% endif %}
          </ul>
          <!--
          <button class="navbar-toggle" , type="button" data-toggle="collapse">
            <span class="navbar-toggler-icon"> </span>
          </button>
        --></nav>
      </header>
      <div class="flash__messages">
        {% with messages = get_flashed_messages(with_categories=true) %} {% if
        messages %} {% for category, message in messages %} {% if category ==
        'error' %}
        <div
          class="alert alert-danger alert-dismissible fade show"
          role="alert"
        >
          {{ message }}
          <button
            type="button"
            class="btn-close"
            data-bs-dismiss="alert"
            aria-label="Close"
          ></button>
        </div>
        {% else %}
        <div
          class="alert alert-success alert-dismissible fade show"
          role="alert"
        >
          {{ message }}
          <button
            type="button"
            class="btn-close"
            data-bs-dismiss="alert"
            aria-label="Close"
          ></button>
        </div>
        {% endif %} {% endfor %} {% endif %} {% endwith %}
      </div>
      {% block content %} {% endblock %}
    </div>
  <footer>
    <div class="bottom__nav">
      <ul class="bottom__nav__one">
        <li>J's Prints Website Information</li>
        <li>Need Help? Contact us at: (EMAIL)</li>
        <li><a href="#">About Us</a></li>
      </ul>
      <ul class="bottom__nav__two">
        <li><a href="#">Contact Us</a></li>
        <li><a href="#">Orders</a></li>
        <li><a href="#">Account</a></li>
      </ul>
      <ul>
        <li><a href="#">Payments</a></li>
      </ul>
    </div>
  </footer>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
    <script type="text/javascript" src="{{ url_for('static', filename='main.js') }}"></script>
</body>
</html>

ecommerce/templates/index.html
{% extends "base.html" %} {% block title%} J's Prints {% endblock %} {% block
content %}
<div id="outer-main">
  <div id="main">
    <div id="main-welcome">
      <h1 id="welcome">Welcome to J's Prints!</h1>
    </div>
    <div id="main-text">
      <p>
        We are dedicated to providing you with high quality prints of special
        moments you want to remember everday. We have a wide variety of prints
        delivered fast to your door and guarenteed to make you smile!
      </p>
    </div>
  </div>
</div>
<div id="lower__nav">
  <nav id="nav__lower">
    <ul id="lower__nav__links">
      <li>
        <a href="#"><button>Contact Us</button></a>
      </li>
      <li>
        <a href="{{ url_for('routes.products') }}"><button>Shop Now</button></a>
      </li>
    </ul>
  </nav>
</div>
{% endblock %}

ecommerce/templates/login.html
{% extends "base.html" %} {% block title%} Login {% endblock %} {% block content
%}
<div id="login__outer__main">
  <div id="inner__main">
    <form action="/login" method="POST" class="form" id="login__main">
      <h1 id="login__title">Login</h1>
      <div class="login__message login__message--error"></div>
      <div class="login__input__group">
        <input
          type="text"
          class="login__input"
          name="username__or__email"
          autofocus
          placeholder="Username or Email"
        />
        <div class="login__input-error-message"></div>
      </div>
      <div class="login__input__group">
        <input
          type="password"
          class="login__input"
          name="login__password"
          autofocus
          placeholder="Password"
        />
        <div class="login__input-error-message"></div>
      </div>
      <button class="login__button" type="submit" id="login__submit">
        Log in
      </button>
      <p class="login__text">
        <a href="#" class="form__link">Forgot your password?</a>
      </p>
      <p class="form__text">
        <a
          class="form__link"
          id="linkCreateAccount"
          href=" {{ url_for('authentication.signup') }}"
          >Don't have an account? Create account</a
        >
      </p>
    </form>
  </div>
</div>
{% endblock %}

ecommerce/templates/productDisplay.html
{% extends "base.html" %} {% block title%} {{ product.name }} {% endblock %} {% block content
%}
<div id="outer__shopping__cart">
  <div class="shopping__cart" id="shopping__cart__main">
    <div class="product__popup__content" id="product__popup__box__main">
      <div id="product__popup__content__title__img">
        <h1 id="product__name">{{ product.product_name }} </h1>
        <img class="product__img" id="product__image" src="{{ url_for('static', filename='UPLOAD_FOLDER/' + product.filename)}}" />
      </div>
      <div id="product__popup__content__info">
        <ul id="product__important__info__list">
          <li>{{ owner.user_name }} </li>
          <li>Unrated</li>
          <li> {% if location %} <strong>{{ location }} </strong> {% else %} <strong>Unknown</strong>  {% endif %} </li>
        </ul>
        <div class="product__popup__content__element" id="product__desc">
          <p>{{ product.prod_desc }}</p>
        </div>
        <form class="add__to__cart" method="POST">
          <button type="submit" id="add__to__cart__button">Add to cart</button>
        </form>
      </div>
    </div>
  </div>
</div>
  </div>
</div>
{% endblock %}

ecommerce/templates/products.html
{% extends "base.html" %} {% block title%} Products {% endblock %} {% block
content %}
<div class="outer__product__page">
  <div class="product__main__category" id="product__main__category">
    <h1 id="main__category">J's Prints Shop!</h1>
    {% if user.is_authenticated %}
    <a
      href="{{ url_for('routes.addProduct')}}"
      class="button"
      id="product__button"
      name="product__button"
    >
      Sell your own print!
    </a>
    {% else %}
    <a
      href="{{ url_for('authentication.login')}}"
      class="button"
      id="product__button"
      name="product__button"
    >
      Sell your own print!
    </a>
    {% endif %}
  </div>
  <div id="product__content">
    <div id="product__sidebar">
      <a
        href="{{ url_for('routes.products')}}"
        class="side__bar__links"
        id="side__link"
        >All</a
      >
      {% for prod in products %}
      <a
        href="{{ url_for('routes.products_by_category', category=prod.category)}}"
        class="side__bar__links"
        id="side__link"
        >{{ prod.category }}</a
      >
      {% endfor %}
    </div>
    <div class="product__showcase__main" id="products__showcase">
      {% if curr_category %}
      <div class="product__page__category">
        <h3 id="product_category">{{ curr_category }}</h3>
      </div>
      {% for prod in prod_by_category %}
      <a
        href="{{ url_for('routes.productDisplay', product_id=prod.product_id) }}"
        class="product__box"
      >
        <div class="product__name" id="product__name__div">
          <h1 id="product__name__title" class="product__name">
            {{ prod.product_name }}
          </h1>
        </div>
        <img
          class="product__img"
          src="{{ url_for('static', filename='UPLOAD_FOLDER/' + prod.filename)}}"
        />
      </a>
      {% endfor %}
    </div>
    {% else %}
    <div class="product__page__category">
      <h3 id="product_category">All Prints!</h3>
    </div>
    {% for prod in products %}
    <a
      href="{{ url_for('routes.productDisplay', product_id=prod.product_id) }}"
      class="product__box"
    >
      <div class="product__name" id="product__name__div">
        <h1 id="product__name__title" class="product__name">
          {{ prod.product_name }}
        </h1>
      </div>
      <img
        class="product__img"
        src="{{ url_for('static', filename='UPLOAD_FOLDER/' + prod.filename)}}"
      />
    </a>
    {% endfor %} {% endif %}
  </div>
</div>
{% endblock %}

ecommerce/templates/signup.html
{% extends "base.html" %} {% block title%} Create an Account {% endblock %} {%
block content %}
<div id="signup__outer__main">
  <div id="signup__main">
    <form action="/signup" method="POST" class="form" id="createAccount">
      <h1 id="signup__title">Create Account</h1>
      <div class="signup__input__group" id="f__and__l__name">
        <div id="f__name">
          <input
            type="text"
            class="signup__input"
            name="signUpFirstName"
            autofocus
            placeholder="First Name"
          />
        </div>
        <div id="l__name">
          <input
            type="text"
            class="signup__input"
            name="signUpLastName"
            autofocus
            placeholder="Last Name"
          />
        </div>
      </div>
      <div class="signup__input__group">
        <input
          type="text"
          id="signUpUserName"
          class="signup__input"
          name="signUpUsername"
          autofocus
          placeholder="Username"
        />
      </div>
      <div class="signup__input__group">
        <input
          type="text"
          id="signUpEmail"
          class="signup__input"
          name="signUpEmail"
          autofocus
          placeholder="Email"
        />
      </div>
      <div class="signup__input__group">
        <input
          type="text"
          id="signUpPhoneNum"
          class="signup__input"
          name="signUpPhoneNum"
          autofocus
          placeholder="Phone Number (Optional)"
        />
      </div>
      <div class="signup__input__group">
        <input
          type="password"
          id="signUpPass"
          class="signup__input"
          name="password1"
          autofocus
          placeholder="Password"
        />
      </div>
      <div class="signup__input__group">
        <input
          type="password"
          class="signup__input"
          id="signUpPass2"
          name="password2"
          autofocus
          placeholder="Re-enter Password"
        />
      </div>
      <button
        class="signup__button"
        type="submit"
        id="create__acc__submit"
        name="create__acc__submit"
      >
        Create Account
      </button>
      <p class="signup__text">
        <a
          class="form__link"
          id="linkLogin"
          href=" {{ url_for('authentication.login')}}"
          >Already have an account? Sign in.</a
        >
      </p>
    </form>
  </div>
</div>
{% endblock %}